title: Griffith University Library Open Lessons
description: A number of research-related self-paced lessons created by Griffith University library staff for use and re-use.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
